# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("source_url", models.URLField(blank=True, default="")),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ForecastJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching", "Fetching price history"),
                            ("training", "Training models"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="products.product",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PricePoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_points",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
                "unique_together": {("product", "recorded_at")},
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("arima", "ARIMA"),
                            ("sarima", "SARIMA"),
                            ("arimax", "ARIMAX"),
                            ("sarimax", "SARIMAX"),
                            ("prophet", "Prophet"),
                            ("garch", "GARCH"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("params", models.JSONField(default=dict)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("mape", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("mlflow_run_id", models.CharField(blank=True, default="", max_length=100)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("is_best", models.BooleanField(default=False)),
                ("is_comparable", models.BooleanField(default=True)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_results",
                        to="products.forecastjob",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="products.product",
                    ),
                ),
            ],
            options={"ordering": ["mae"]},
        ),
    ]
