# Generated by Codex on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalDipModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=500)),
                ("params", models.JSONField(default=dict)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("product_count", models.PositiveIntegerField(default=0)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="DipPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("price_as_of", models.DateTimeField(db_index=True)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dip_threshold", models.FloatField(default=0.05)),
                ("horizon_days", models.PositiveIntegerField(default=30)),
                ("probabilities", models.JSONField(default=dict)),
                ("expected_dip_date", models.DateField(blank=True, null=True)),
                ("expected_dip_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("confidence", models.CharField(default="low", max_length=20)),
                ("recommendation", models.CharField(default="watch", max_length=20)),
                ("reason", models.TextField(blank=True, default="")),
                ("features", models.JSONField(default=dict)),
                ("global_model", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="predictions", to="products.globaldipmodel")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dip_predictions", to="products.product")),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dipprediction",
            index=models.Index(fields=["product", "price_as_of"], name="products_di_product_20bb5f_idx"),
        ),
    ]